language: go
dist: trusty
os:
    - linux
    - osx
go:
    - 1.7
addons:
    apt:
        packages:
            - git
    

before_install:
    - git config -l
    - git --version
    - hg --version

script:
    - bash test.sh
after_success:
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov coverage report upload error"
